server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: tourist-service
          uri: http://localhost:4001
          predicates:
            - Path=/api/v1/tourists/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - OPTIONS
              allowedHeaders: "*"
              allowCredentials: true